apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-camel-amq-config
data:
  url: tcp://amq-svc.broker.svc.cluster.local:61616
  userName: admin
  password: admin
  queues: sendq
  queuer: recvq
  maxConnections: "25"
  maxSessionsPerConnection: "1"